INSERT INTO CLIENT(NOM,PRENOM,IDENTIFIANT,PWD) VALUES('Winchester','Dean','WinD', 'pwd');
INSERT INTO CLIENT(NOM,PRENOM,IDENTIFIANT,PWD) VALUES('Winchester','Sammy','WinS', 'pwd');
INSERT INTO CLIENT(NOM,PRENOM,IDENTIFIANT,PWD) VALUES('Dunno','Ellen','DunnE', 'pwd');
INSERT INTO CLIENT(NOM,PRENOM,IDENTIFIANT,PWD) VALUES('Dunno','Bobby','DunnB', 'pwd');
INSERT INTO CLIENT(NOM,PRENOM,IDENTIFIANT,PWD) VALUES('Dunno','Jo','DunnJ', 'pwd');